- Target: nmaguiar/socksd:latest (alpine 3.18.4)
  Class: os-pkgs
  Type: alpine
- Target: Java
  Class: lang-pkgs
  Type: jar
  Vulnerabilities:
  - VulnerabilityID: CVE-2023-6378
    PkgName: ch.qos.logback:logback-classic
    PkgPath: openaf/openaf.jar
    InstalledVersion: 1.2.11
    FixedVersion: 1.3.12, 1.4.12, 1.2.13
    Status: fixed
    Layer:
      Digest: sha256:b186c21e964785dd9f314535d3b9abba3693f892ebbd606ea7611052ecd1e396
      DiffID: sha256:b6717f72067520b7670ae30f3a71d32dc20f9bf4a891055499495d4bb5e2725a
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-6378
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'logback: serialization vulnerability in logback receiver'
    Description: |+
      A serialization vulnerability in logback receiver component part of 
      logback version 1.4.11 allows an attacker to mount a Denial-Of-Service 
      attack by sending poisoned data.

    Severity: HIGH
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:H
        V3Score: 7.1
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:H
        V3Score: 7.1
    References:
    - https://access.redhat.com/security/cve/CVE-2023-6378
    - https://github.com/qos-ch/logback
    - https://github.com/qos-ch/logback/commit/9c782b45be4abdafb7e17481e24e7354c2acd1eb
    - https://github.com/qos-ch/logback/commit/b8eac23a9de9e05fb6d51160b3f46acd91af9731
    - https://github.com/qos-ch/logback/commit/bb095154be011267b64e37a1d401546e7cc2b7c3
    - https://github.com/qos-ch/logback/issues/745#issuecomment-1836227158
    - https://logback.qos.ch/manual/receivers.html
    - https://logback.qos.ch/news.html#1.2.13
    - https://logback.qos.ch/news.html#1.3.12
    - https://nvd.nist.gov/vuln/detail/CVE-2023-6378
    - https://www.cve.org/CVERecord?id=CVE-2023-6378
    PublishedDate: '2023-11-29T12:15:00Z'
    LastModifiedDate: '2023-11-29T14:18:00Z'
  - VulnerabilityID: CVE-2023-6378
    PkgName: ch.qos.logback:logback-core
    PkgPath: openaf/openaf.jar
    InstalledVersion: 1.2.11
    FixedVersion: 1.3.12, 1.4.12, 1.2.13
    Status: fixed
    Layer:
      Digest: sha256:b186c21e964785dd9f314535d3b9abba3693f892ebbd606ea7611052ecd1e396
      DiffID: sha256:b6717f72067520b7670ae30f3a71d32dc20f9bf4a891055499495d4bb5e2725a
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-6378
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'logback: serialization vulnerability in logback receiver'
    Description: |+
      A serialization vulnerability in logback receiver component part of 
      logback version 1.4.11 allows an attacker to mount a Denial-Of-Service 
      attack by sending poisoned data.

    Severity: HIGH
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:H
        V3Score: 7.1
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:H
        V3Score: 7.1
    References:
    - https://access.redhat.com/security/cve/CVE-2023-6378
    - https://github.com/qos-ch/logback
    - https://github.com/qos-ch/logback/commit/9c782b45be4abdafb7e17481e24e7354c2acd1eb
    - https://github.com/qos-ch/logback/commit/b8eac23a9de9e05fb6d51160b3f46acd91af9731
    - https://github.com/qos-ch/logback/commit/bb095154be011267b64e37a1d401546e7cc2b7c3
    - https://github.com/qos-ch/logback/issues/745#issuecomment-1836227158
    - https://logback.qos.ch/manual/receivers.html
    - https://logback.qos.ch/news.html#1.2.13
    - https://logback.qos.ch/news.html#1.3.12
    - https://nvd.nist.gov/vuln/detail/CVE-2023-6378
    - https://www.cve.org/CVERecord?id=CVE-2023-6378
    PublishedDate: '2023-11-29T12:15:00Z'
    LastModifiedDate: '2023-11-29T14:18:00Z'
