- Target: nmaguiar/socksd:build (alpine 3.19.1)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2023-42366
    PkgID: busybox@1.36.1-r15
    PkgName: busybox
    PkgIdentifier:
      PURL: pkg:apk/alpine/busybox@1.36.1-r15?arch=x86_64&distro=3.19.1
      UID: a71bca140ff5726b
    InstalledVersion: 1.36.1-r15
    FixedVersion: 1.36.1-r16
    Status: fixed
    Layer:
      Digest: sha256:6573841e7552d819410e7673b8e02138f4159022593e40112126d99433fbfc79
      DiffID: sha256:390e72f6be6680bc1cb119e5bcfe99f2a09ac33a6db3da60cc52b524756156a0
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42366
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox: A heap-buffer-overflow'
    Description: A heap-buffer-overflow was discovered in BusyBox v.1.36.1 in the next_token function at awk.c:1159.
    Severity: MEDIUM
    CweIDs:
    - CWE-787
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:H
        V3Score: 7.1
    References:
    - https://access.redhat.com/security/cve/CVE-2023-42366
    - https://bugs.busybox.net/show_bug.cgi?id=15874
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42366
    - https://www.cve.org/CVERecord?id=CVE-2023-42366
    PublishedDate: '2023-11-27T23:15:07.42Z'
    LastModifiedDate: '2023-11-30T05:08:23.197Z'
  - VulnerabilityID: CVE-2023-42366
    PkgID: busybox-binsh@1.36.1-r15
    PkgName: busybox-binsh
    PkgIdentifier:
      PURL: pkg:apk/alpine/busybox-binsh@1.36.1-r15?arch=x86_64&distro=3.19.1
      UID: 3c2acc699fbc7b01
    InstalledVersion: 1.36.1-r15
    FixedVersion: 1.36.1-r16
    Status: fixed
    Layer:
      Digest: sha256:6573841e7552d819410e7673b8e02138f4159022593e40112126d99433fbfc79
      DiffID: sha256:390e72f6be6680bc1cb119e5bcfe99f2a09ac33a6db3da60cc52b524756156a0
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42366
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox: A heap-buffer-overflow'
    Description: A heap-buffer-overflow was discovered in BusyBox v.1.36.1 in the next_token function at awk.c:1159.
    Severity: MEDIUM
    CweIDs:
    - CWE-787
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:H
        V3Score: 7.1
    References:
    - https://access.redhat.com/security/cve/CVE-2023-42366
    - https://bugs.busybox.net/show_bug.cgi?id=15874
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42366
    - https://www.cve.org/CVERecord?id=CVE-2023-42366
    PublishedDate: '2023-11-27T23:15:07.42Z'
    LastModifiedDate: '2023-11-30T05:08:23.197Z'
  - VulnerabilityID: CVE-2023-42366
    PkgID: ssl_client@1.36.1-r15
    PkgName: ssl_client
    PkgIdentifier:
      PURL: pkg:apk/alpine/ssl_client@1.36.1-r15?arch=x86_64&distro=3.19.1
      UID: 3a57d387f26109e5
    InstalledVersion: 1.36.1-r15
    FixedVersion: 1.36.1-r16
    Status: fixed
    Layer:
      Digest: sha256:6573841e7552d819410e7673b8e02138f4159022593e40112126d99433fbfc79
      DiffID: sha256:390e72f6be6680bc1cb119e5bcfe99f2a09ac33a6db3da60cc52b524756156a0
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42366
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox: A heap-buffer-overflow'
    Description: A heap-buffer-overflow was discovered in BusyBox v.1.36.1 in the next_token function at awk.c:1159.
    Severity: MEDIUM
    CweIDs:
    - CWE-787
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:H
        V3Score: 7.1
    References:
    - https://access.redhat.com/security/cve/CVE-2023-42366
    - https://bugs.busybox.net/show_bug.cgi?id=15874
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42366
    - https://www.cve.org/CVERecord?id=CVE-2023-42366
    PublishedDate: '2023-11-27T23:15:07.42Z'
    LastModifiedDate: '2023-11-30T05:08:23.197Z'
