- Target: nmaguiar/socksd:build (alpine 3.18.4)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2023-43787
    PkgID: libx11@1.8.4-r4
    PkgName: libx11
    InstalledVersion: 1.8.4-r4
    FixedVersion: 1.8.7-r0
    Status: fixed
    Layer:
      Digest: sha256:3238db5dc7ddb46d8d67f3fa060e58d22cc1284dc8ecfec9ea36f2482a363888
      DiffID: sha256:63bd1d5288e5bf21330664d403292c931e3ad45c1df2e97d12b2fd5482aa675e
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-43787
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: integer overflow in XCreateImage() leading to a heap overflow
    Description: A vulnerability was found in libX11 due to an integer overflow within the XCreateImage() function. This flaw allows a local user to trigger an integer overflow and execute arbitrary code with elevated privileges.
    Severity: HIGH
    CweIDs:
    - CWE-190
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H
        V3Score: 7.8
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - https://access.redhat.com/security/cve/CVE-2023-43787
    - https://bugzilla.redhat.com/show_bug.cgi?id=2242254
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-43787
    - https://nvd.nist.gov/vuln/detail/CVE-2023-43787
    - https://ubuntu.com/security/notices/USN-6407-1
    - https://ubuntu.com/security/notices/USN-6407-2
    - https://ubuntu.com/security/notices/USN-6408-1
    - https://ubuntu.com/security/notices/USN-6408-2
    - https://www.cve.org/CVERecord?id=CVE-2023-43787
    PublishedDate: '2023-10-10T13:15:00Z'
    LastModifiedDate: '2023-10-13T13:18:00Z'
  - VulnerabilityID: CVE-2023-43785
    PkgID: libx11@1.8.4-r4
    PkgName: libx11
    InstalledVersion: 1.8.4-r4
    FixedVersion: 1.8.7-r0
    Status: fixed
    Layer:
      Digest: sha256:3238db5dc7ddb46d8d67f3fa060e58d22cc1284dc8ecfec9ea36f2482a363888
      DiffID: sha256:63bd1d5288e5bf21330664d403292c931e3ad45c1df2e97d12b2fd5482aa675e
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-43785
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: out-of-bounds memory access in _XkbReadKeySyms()
    Description: A vulnerability was found in libX11 due to a boundary condition within the _XkbReadKeySyms() function. This flaw allows a local user to trigger an out-of-bounds read error and read the contents of memory on the system.
    Severity: MEDIUM
    CweIDs:
    - CWE-125
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:N
        V3Score: 6.5
    References:
    - https://access.redhat.com/security/cve/CVE-2023-43785
    - https://bugzilla.redhat.com/show_bug.cgi?id=2242252
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-43785
    - https://nvd.nist.gov/vuln/detail/CVE-2023-43785
    - https://ubuntu.com/security/notices/USN-6407-1
    - https://ubuntu.com/security/notices/USN-6407-2
    - https://www.cve.org/CVERecord?id=CVE-2023-43785
    PublishedDate: '2023-10-10T13:15:00Z'
    LastModifiedDate: '2023-10-12T19:03:00Z'
  - VulnerabilityID: CVE-2023-43786
    PkgID: libx11@1.8.4-r4
    PkgName: libx11
    InstalledVersion: 1.8.4-r4
    FixedVersion: 1.8.7-r0
    Status: fixed
    Layer:
      Digest: sha256:3238db5dc7ddb46d8d67f3fa060e58d22cc1284dc8ecfec9ea36f2482a363888
      DiffID: sha256:63bd1d5288e5bf21330664d403292c931e3ad45c1df2e97d12b2fd5482aa675e
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-43786
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: stack exhaustion from infinite recursion in PutSubImage()
    Description: A vulnerability was found in libX11 due to an infinite loop within the PutSubImage() function. This flaw allows a local user to consume all available system resources and cause a denial of service condition.
    Severity: MEDIUM
    CweIDs:
    - CWE-835
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
    References:
    - https://access.redhat.com/security/cve/CVE-2023-43786
    - https://bugzilla.redhat.com/show_bug.cgi?id=2242253
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-43786
    - https://nvd.nist.gov/vuln/detail/CVE-2023-43786
    - https://ubuntu.com/security/notices/USN-6407-1
    - https://ubuntu.com/security/notices/USN-6407-2
    - https://ubuntu.com/security/notices/USN-6408-1
    - https://ubuntu.com/security/notices/USN-6408-2
    - https://www.cve.org/CVERecord?id=CVE-2023-43786
    PublishedDate: '2023-10-10T13:15:00Z'
    LastModifiedDate: '2023-10-13T13:26:00Z'
