stdout: {}
stderr: |
  docker: Error response from daemon: Head "https://registry-1.docker.io/v2/aquasec/trivy/manifests/latest": EOF.
  See 'docker run --help'.
exitcode: 125
cmd: docker run --pull always --rm  aquasec/trivy -f json  image nmaguiar/socksd:ubi-build
