- Target: nmaguiar/socksd:latest (alpine 3.21.2)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-13176
    PkgID: libcrypto3@3.3.2-r4
    PkgName: libcrypto3
    PkgIdentifier:
      PURL: pkg:apk/alpine/libcrypto3@3.3.2-r4?arch=x86_64&distro=3.21.2
      UID: 542067a84ab82f32
    InstalledVersion: 3.3.2-r4
    FixedVersion: 3.3.2-r5
    Status: fixed
    Layer:
      Digest: sha256:750127bea5a0be4ae46b3e4fcb6e83f22014f5548be025edb95d32b18819875f
      DiffID: sha256:22bfcd25d985c8d80cc7e5d7166dd0b72c8b85f314193f5004fd1a4b7abc9b8c
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-13176
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'openssl: Timing side-channel in ECDSA signature computation'
    Description: |-
      Issue summary: A timing side-channel which could potentially allow recovering
      the private key exists in the ECDSA signature computation.

      Impact summary: A timing side-channel in ECDSA signature computations
      could allow recovering the private key by an attacker. However, measuring
      the timing would require either local access to the signing application or
      a very fast network connection with low latency.

      There is a timing signal of around 300 nanoseconds when the top word of
      the inverted ECDSA nonce value is zero. This can happen with significant
      probability only for some of the supported elliptic curves. In particular
      the NIST P-521 curve is affected. To be able to measure this leak, the attacker
      process must either be located in the same physical computer or must
      have a very fast network connection with low latency. For that reason
      the severity of this vulnerability is Low.
    Severity: MEDIUM
    CweIDs:
    - CWE-385
    VendorSeverity:
      amazon: 2
      redhat: 1
      ubuntu: 1
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N
        V3Score: 4.7
    References:
    - http://www.openwall.com/lists/oss-security/2025/01/20/2
    - https://access.redhat.com/security/cve/CVE-2024-13176
    - https://github.com/openssl/openssl/commit/07272b05b04836a762b4baa874958af51d513844
    - https://github.com/openssl/openssl/commit/2af62e74fb59bc469506bc37eb2990ea408d9467
    - https://github.com/openssl/openssl/commit/392dcb336405a0c94486aa6655057f59fd3a0902
    - https://github.com/openssl/openssl/commit/4b1cb94a734a7d4ec363ac0a215a25c181e11f65
    - https://github.com/openssl/openssl/commit/77c608f4c8857e63e98e66444e2e761c9627916f
    - https://github.openssl.org/openssl/extended-releases/commit/0d5fd1ab987f7571e2c955d8d8b638fc0fb54ded
    - https://github.openssl.org/openssl/extended-releases/commit/a2639000db19878d5d89586ae7b725080592ae86
    - https://nvd.nist.gov/vuln/detail/CVE-2024-13176
    - https://openssl-library.org/news/secadv/20250120.txt
    - https://security.netapp.com/advisory/ntap-20250124-0005/
    - https://www.cve.org/CVERecord?id=CVE-2024-13176
    PublishedDate: '2025-01-20T14:15:26.247Z'
    LastModifiedDate: '2025-01-27T21:15:11.907Z'
  - VulnerabilityID: CVE-2024-13176
    PkgID: libssl3@3.3.2-r4
    PkgName: libssl3
    PkgIdentifier:
      PURL: pkg:apk/alpine/libssl3@3.3.2-r4?arch=x86_64&distro=3.21.2
      UID: b53306887f53ea89
    InstalledVersion: 3.3.2-r4
    FixedVersion: 3.3.2-r5
    Status: fixed
    Layer:
      Digest: sha256:750127bea5a0be4ae46b3e4fcb6e83f22014f5548be025edb95d32b18819875f
      DiffID: sha256:22bfcd25d985c8d80cc7e5d7166dd0b72c8b85f314193f5004fd1a4b7abc9b8c
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-13176
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'openssl: Timing side-channel in ECDSA signature computation'
    Description: |-
      Issue summary: A timing side-channel which could potentially allow recovering
      the private key exists in the ECDSA signature computation.

      Impact summary: A timing side-channel in ECDSA signature computations
      could allow recovering the private key by an attacker. However, measuring
      the timing would require either local access to the signing application or
      a very fast network connection with low latency.

      There is a timing signal of around 300 nanoseconds when the top word of
      the inverted ECDSA nonce value is zero. This can happen with significant
      probability only for some of the supported elliptic curves. In particular
      the NIST P-521 curve is affected. To be able to measure this leak, the attacker
      process must either be located in the same physical computer or must
      have a very fast network connection with low latency. For that reason
      the severity of this vulnerability is Low.
    Severity: MEDIUM
    CweIDs:
    - CWE-385
    VendorSeverity:
      amazon: 2
      redhat: 1
      ubuntu: 1
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N
        V3Score: 4.7
    References:
    - http://www.openwall.com/lists/oss-security/2025/01/20/2
    - https://access.redhat.com/security/cve/CVE-2024-13176
    - https://github.com/openssl/openssl/commit/07272b05b04836a762b4baa874958af51d513844
    - https://github.com/openssl/openssl/commit/2af62e74fb59bc469506bc37eb2990ea408d9467
    - https://github.com/openssl/openssl/commit/392dcb336405a0c94486aa6655057f59fd3a0902
    - https://github.com/openssl/openssl/commit/4b1cb94a734a7d4ec363ac0a215a25c181e11f65
    - https://github.com/openssl/openssl/commit/77c608f4c8857e63e98e66444e2e761c9627916f
    - https://github.openssl.org/openssl/extended-releases/commit/0d5fd1ab987f7571e2c955d8d8b638fc0fb54ded
    - https://github.openssl.org/openssl/extended-releases/commit/a2639000db19878d5d89586ae7b725080592ae86
    - https://nvd.nist.gov/vuln/detail/CVE-2024-13176
    - https://openssl-library.org/news/secadv/20250120.txt
    - https://security.netapp.com/advisory/ntap-20250124-0005/
    - https://www.cve.org/CVERecord?id=CVE-2024-13176
    PublishedDate: '2025-01-20T14:15:26.247Z'
    LastModifiedDate: '2025-01-27T21:15:11.907Z'
  - VulnerabilityID: CVE-2024-12133
    PkgID: libtasn1@4.19.0-r2
    PkgName: libtasn1
    PkgIdentifier:
      PURL: pkg:apk/alpine/libtasn1@4.19.0-r2?arch=x86_64&distro=3.21.2
      UID: 7578a1741187c1a2
    InstalledVersion: 4.19.0-r2
    FixedVersion: 4.20.0-r0
    Status: fixed
    Layer:
      Digest: sha256:750127bea5a0be4ae46b3e4fcb6e83f22014f5548be025edb95d32b18819875f
      DiffID: sha256:22bfcd25d985c8d80cc7e5d7166dd0b72c8b85f314193f5004fd1a4b7abc9b8c
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-12133
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'libtasn1: Inefficient DER Decoding in libtasn1 Leading to Potential Remote DoS'
    Description: A flaw in libtasn1 causes inefficient handling of specific certificate data. When processing a large number of elements in a certificate, libtasn1 takes much longer than expected, which can slow down or even crash the system. This flaw allows an attacker to send a specially crafted certificate, causing a denial of service attack.
    Severity: MEDIUM
    CweIDs:
    - CWE-407
    VendorSeverity:
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L
        V3Score: 5.3
    References:
    - http://www.openwall.com/lists/oss-security/2025/02/06/6
    - https://access.redhat.com/security/cve/CVE-2024-12133
    - https://bugzilla.redhat.com/show_bug.cgi?id=2344611
    - https://gitlab.com/gnutls/libtasn1/-/issues/52
    - https://nvd.nist.gov/vuln/detail/CVE-2024-12133
    - https://www.cve.org/CVERecord?id=CVE-2024-12133
    PublishedDate: '2025-02-10T16:15:37.26Z'
    LastModifiedDate: '2025-02-10T16:15:37.26Z'
  - VulnerabilityID: CVE-2025-21502
    PkgID: openjdk21-jre@21.0.5_p11-r0
    PkgName: openjdk21-jre
    PkgIdentifier:
      PURL: pkg:apk/alpine/openjdk21-jre@21.0.5_p11-r0?arch=x86_64&distro=3.21.2
      UID: a5d9a18655dffa68
    InstalledVersion: 21.0.5_p11-r0
    FixedVersion: 21.0.6_p7-r0
    Status: fixed
    Layer:
      Digest: sha256:750127bea5a0be4ae46b3e4fcb6e83f22014f5548be025edb95d32b18819875f
      DiffID: sha256:22bfcd25d985c8d80cc7e5d7166dd0b72c8b85f314193f5004fd1a4b7abc9b8c
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-21502
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'JDK: Enhance array handling (Oracle CPU 2025-01)'
    Description: 'Vulnerability in the Oracle Java SE, Oracle GraalVM for JDK, Oracle GraalVM Enterprise Edition product of Oracle Java SE (component: Hotspot).  Supported versions that are affected are Oracle Java SE: 8u431-perf, 11.0.25, 17.0.13, 21.0.5, 23.0.1; Oracle GraalVM for JDK: 17.0.13, 21.0.5, 23.0.1; Oracle GraalVM Enterprise Edition: 20.3.16 and  21.3.12. Difficult to exploit vulnerability allows unauthenticated attacker with network access via multiple protocols to compromise Oracle Java SE, Oracle GraalVM for JDK, Oracle GraalVM Enterprise Edition.  Successful attacks of this vulnerability can result in  unauthorized update, insert or delete access to some of Oracle Java SE, Oracle GraalVM for JDK, Oracle GraalVM Enterprise Edition accessible data as well as  unauthorized read access to a subset of Oracle Java SE, Oracle GraalVM for JDK, Oracle GraalVM Enterprise Edition accessible data. Note: This vulnerability can be exploited by using APIs in the specified Component, e.g., through a web service which supplies data to the APIs. This vulnerability also applies to Java deployments, typically in clients running sandboxed Java Web Start applications or sandboxed Java applets, that load and run untrusted code (e.g., code that comes from the internet) and rely on the Java sandbox for security. CVSS 3.1 Base Score 4.8 (Confidentiality and Integrity impacts).  CVSS Vector: (CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N).'
    Severity: MEDIUM
    CweIDs:
    - CWE-863
    VendorSeverity:
      alma: 2
      amazon: 2
      oracle-oval: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N
        V3Score: 4.8
    References:
    - http://www.openwall.com/lists/oss-security/2025/01/25/6
    - https://access.redhat.com/errata/RHSA-2025:0426
    - https://access.redhat.com/security/cve/CVE-2025-21502
    - https://errata.almalinux.org/9/ALSA-2025-0426.html
    - https://linux.oracle.com/cve/CVE-2025-21502.html
    - https://linux.oracle.com/errata/ELSA-2025-0426.html
    - https://lists.debian.org/debian-lts-announce/2025/01/msg00031.html
    - https://lists.debian.org/debian-lts-announce/2025/02/msg00004.html
    - https://nvd.nist.gov/vuln/detail/CVE-2025-21502
    - https://security.netapp.com/advisory/ntap-20250124-0009/
    - https://ubuntu.com/security/notices/USN-7252-1
    - https://ubuntu.com/security/notices/USN-7253-1
    - https://ubuntu.com/security/notices/USN-7254-1
    - https://ubuntu.com/security/notices/USN-7255-1
    - https://www.cve.org/CVERecord?id=CVE-2025-21502
    - https://www.oracle.com/security-alerts/cpujan2025.html
    - https://www.oracle.com/security-alerts/cpujan2025.html#AppendixJAVA
    PublishedDate: '2025-01-21T21:15:15.18Z'
    LastModifiedDate: '2025-02-07T11:15:10.717Z'
  - VulnerabilityID: CVE-2025-21502
    PkgID: openjdk21-jre-headless@21.0.5_p11-r0
    PkgName: openjdk21-jre-headless
    PkgIdentifier:
      PURL: pkg:apk/alpine/openjdk21-jre-headless@21.0.5_p11-r0?arch=x86_64&distro=3.21.2
      UID: 38dfd3a16561ba17
    InstalledVersion: 21.0.5_p11-r0
    FixedVersion: 21.0.6_p7-r0
    Status: fixed
    Layer:
      Digest: sha256:750127bea5a0be4ae46b3e4fcb6e83f22014f5548be025edb95d32b18819875f
      DiffID: sha256:22bfcd25d985c8d80cc7e5d7166dd0b72c8b85f314193f5004fd1a4b7abc9b8c
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-21502
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'JDK: Enhance array handling (Oracle CPU 2025-01)'
    Description: 'Vulnerability in the Oracle Java SE, Oracle GraalVM for JDK, Oracle GraalVM Enterprise Edition product of Oracle Java SE (component: Hotspot).  Supported versions that are affected are Oracle Java SE: 8u431-perf, 11.0.25, 17.0.13, 21.0.5, 23.0.1; Oracle GraalVM for JDK: 17.0.13, 21.0.5, 23.0.1; Oracle GraalVM Enterprise Edition: 20.3.16 and  21.3.12. Difficult to exploit vulnerability allows unauthenticated attacker with network access via multiple protocols to compromise Oracle Java SE, Oracle GraalVM for JDK, Oracle GraalVM Enterprise Edition.  Successful attacks of this vulnerability can result in  unauthorized update, insert or delete access to some of Oracle Java SE, Oracle GraalVM for JDK, Oracle GraalVM Enterprise Edition accessible data as well as  unauthorized read access to a subset of Oracle Java SE, Oracle GraalVM for JDK, Oracle GraalVM Enterprise Edition accessible data. Note: This vulnerability can be exploited by using APIs in the specified Component, e.g., through a web service which supplies data to the APIs. This vulnerability also applies to Java deployments, typically in clients running sandboxed Java Web Start applications or sandboxed Java applets, that load and run untrusted code (e.g., code that comes from the internet) and rely on the Java sandbox for security. CVSS 3.1 Base Score 4.8 (Confidentiality and Integrity impacts).  CVSS Vector: (CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N).'
    Severity: MEDIUM
    CweIDs:
    - CWE-863
    VendorSeverity:
      alma: 2
      amazon: 2
      oracle-oval: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N
        V3Score: 4.8
    References:
    - http://www.openwall.com/lists/oss-security/2025/01/25/6
    - https://access.redhat.com/errata/RHSA-2025:0426
    - https://access.redhat.com/security/cve/CVE-2025-21502
    - https://errata.almalinux.org/9/ALSA-2025-0426.html
    - https://linux.oracle.com/cve/CVE-2025-21502.html
    - https://linux.oracle.com/errata/ELSA-2025-0426.html
    - https://lists.debian.org/debian-lts-announce/2025/01/msg00031.html
    - https://lists.debian.org/debian-lts-announce/2025/02/msg00004.html
    - https://nvd.nist.gov/vuln/detail/CVE-2025-21502
    - https://security.netapp.com/advisory/ntap-20250124-0009/
    - https://ubuntu.com/security/notices/USN-7252-1
    - https://ubuntu.com/security/notices/USN-7253-1
    - https://ubuntu.com/security/notices/USN-7254-1
    - https://ubuntu.com/security/notices/USN-7255-1
    - https://www.cve.org/CVERecord?id=CVE-2025-21502
    - https://www.oracle.com/security-alerts/cpujan2025.html
    - https://www.oracle.com/security-alerts/cpujan2025.html#AppendixJAVA
    PublishedDate: '2025-01-21T21:15:15.18Z'
    LastModifiedDate: '2025-02-07T11:15:10.717Z'
  - VulnerabilityID: CVE-2024-13176
    PkgID: openssl@3.3.2-r4
    PkgName: openssl
    PkgIdentifier:
      PURL: pkg:apk/alpine/openssl@3.3.2-r4?arch=x86_64&distro=3.21.2
      UID: c41989a6b9105b63
    InstalledVersion: 3.3.2-r4
    FixedVersion: 3.3.2-r5
    Status: fixed
    Layer:
      Digest: sha256:750127bea5a0be4ae46b3e4fcb6e83f22014f5548be025edb95d32b18819875f
      DiffID: sha256:22bfcd25d985c8d80cc7e5d7166dd0b72c8b85f314193f5004fd1a4b7abc9b8c
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-13176
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'openssl: Timing side-channel in ECDSA signature computation'
    Description: |-
      Issue summary: A timing side-channel which could potentially allow recovering
      the private key exists in the ECDSA signature computation.

      Impact summary: A timing side-channel in ECDSA signature computations
      could allow recovering the private key by an attacker. However, measuring
      the timing would require either local access to the signing application or
      a very fast network connection with low latency.

      There is a timing signal of around 300 nanoseconds when the top word of
      the inverted ECDSA nonce value is zero. This can happen with significant
      probability only for some of the supported elliptic curves. In particular
      the NIST P-521 curve is affected. To be able to measure this leak, the attacker
      process must either be located in the same physical computer or must
      have a very fast network connection with low latency. For that reason
      the severity of this vulnerability is Low.
    Severity: MEDIUM
    CweIDs:
    - CWE-385
    VendorSeverity:
      amazon: 2
      redhat: 1
      ubuntu: 1
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N
        V3Score: 4.7
    References:
    - http://www.openwall.com/lists/oss-security/2025/01/20/2
    - https://access.redhat.com/security/cve/CVE-2024-13176
    - https://github.com/openssl/openssl/commit/07272b05b04836a762b4baa874958af51d513844
    - https://github.com/openssl/openssl/commit/2af62e74fb59bc469506bc37eb2990ea408d9467
    - https://github.com/openssl/openssl/commit/392dcb336405a0c94486aa6655057f59fd3a0902
    - https://github.com/openssl/openssl/commit/4b1cb94a734a7d4ec363ac0a215a25c181e11f65
    - https://github.com/openssl/openssl/commit/77c608f4c8857e63e98e66444e2e761c9627916f
    - https://github.openssl.org/openssl/extended-releases/commit/0d5fd1ab987f7571e2c955d8d8b638fc0fb54ded
    - https://github.openssl.org/openssl/extended-releases/commit/a2639000db19878d5d89586ae7b725080592ae86
    - https://nvd.nist.gov/vuln/detail/CVE-2024-13176
    - https://openssl-library.org/news/secadv/20250120.txt
    - https://security.netapp.com/advisory/ntap-20250124-0005/
    - https://www.cve.org/CVERecord?id=CVE-2024-13176
    PublishedDate: '2025-01-20T14:15:26.247Z'
    LastModifiedDate: '2025-01-27T21:15:11.907Z'
- Target: Java
  Class: lang-pkgs
  Type: jar
