- Target: nmaguiar/socksd:build (alpine 3.18.4)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2023-46218
    PkgID: curl@8.4.0-r0
    PkgName: curl
    InstalledVersion: 8.4.0-r0
    FixedVersion: 8.5.0-r0
    Status: fixed
    Layer:
      Digest: sha256:488f0b07509d02a094ef807d52d657b749e2dddf7c3dc1c52d5dc096c0aefa0e
      DiffID: sha256:0f53fcd8f118f0b22703fd36f77cdf4c6a6bb5215782ef9bee8de0118fb4efd9
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-46218
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'curl: information disclosure by exploiting a mixed case flaw'
    Description: |
      This flaw allows a malicious HTTP server to set "super cookies" in curl that
      are then passed back to more origins than what is otherwise allowed or
      possible. This allows a site to set cookies that then would get sent to
      different and unrelated sites and domains.

      It could do this by exploiting a mixed case flaw in curl's function that
      verifies a given cookie domain against the Public Suffix List (PSL). For
      example a cookie could be set with `domain=co.UK` when the URL used a lower
      case hostname `curl.co.uk`, even though `co.uk` is listed as a PSL domain.
    Severity: MEDIUM
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
        V3Score: 5.3
    References:
    - https://access.redhat.com/security/cve/CVE-2023-46218
    - https://curl.se/docs/CVE-2023-46218.html
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-46218
    - https://hackerone.com/reports/2212193
    - https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/3ZX3VW67N4ACRAPMV2QS2LVYGD7H2MVE/
    - https://nvd.nist.gov/vuln/detail/CVE-2023-46218
    - https://ubuntu.com/security/notices/USN-6535-1
    - https://www.cve.org/CVERecord?id=CVE-2023-46218
    PublishedDate: '2023-12-07T01:15:00Z'
    LastModifiedDate: '2023-12-10T03:15:00Z'
  - VulnerabilityID: CVE-2023-46219
    PkgID: curl@8.4.0-r0
    PkgName: curl
    InstalledVersion: 8.4.0-r0
    FixedVersion: 8.5.0-r0
    Status: fixed
    Layer:
      Digest: sha256:488f0b07509d02a094ef807d52d657b749e2dddf7c3dc1c52d5dc096c0aefa0e
      DiffID: sha256:0f53fcd8f118f0b22703fd36f77cdf4c6a6bb5215782ef9bee8de0118fb4efd9
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-46219
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'curl: excessively long file name may lead to unknown HSTS status'
    Description: No description is available for this CVE.
    Severity: LOW
    References:
    - https://access.redhat.com/security/cve/CVE-2023-46219
    - https://curl.se/docs/CVE-2023-46219.html
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-46219
    - https://nvd.nist.gov/vuln/detail/CVE-2023-46219
    - https://ubuntu.com/security/notices/USN-6535-1
    - https://www.cve.org/CVERecord?id=CVE-2023-46219
  - VulnerabilityID: CVE-2023-46218
    PkgID: libcurl@8.4.0-r0
    PkgName: libcurl
    InstalledVersion: 8.4.0-r0
    FixedVersion: 8.5.0-r0
    Status: fixed
    Layer:
      Digest: sha256:488f0b07509d02a094ef807d52d657b749e2dddf7c3dc1c52d5dc096c0aefa0e
      DiffID: sha256:0f53fcd8f118f0b22703fd36f77cdf4c6a6bb5215782ef9bee8de0118fb4efd9
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-46218
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'curl: information disclosure by exploiting a mixed case flaw'
    Description: |
      This flaw allows a malicious HTTP server to set "super cookies" in curl that
      are then passed back to more origins than what is otherwise allowed or
      possible. This allows a site to set cookies that then would get sent to
      different and unrelated sites and domains.

      It could do this by exploiting a mixed case flaw in curl's function that
      verifies a given cookie domain against the Public Suffix List (PSL). For
      example a cookie could be set with `domain=co.UK` when the URL used a lower
      case hostname `curl.co.uk`, even though `co.uk` is listed as a PSL domain.
    Severity: MEDIUM
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
        V3Score: 5.3
    References:
    - https://access.redhat.com/security/cve/CVE-2023-46218
    - https://curl.se/docs/CVE-2023-46218.html
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-46218
    - https://hackerone.com/reports/2212193
    - https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/3ZX3VW67N4ACRAPMV2QS2LVYGD7H2MVE/
    - https://nvd.nist.gov/vuln/detail/CVE-2023-46218
    - https://ubuntu.com/security/notices/USN-6535-1
    - https://www.cve.org/CVERecord?id=CVE-2023-46218
    PublishedDate: '2023-12-07T01:15:00Z'
    LastModifiedDate: '2023-12-10T03:15:00Z'
  - VulnerabilityID: CVE-2023-46219
    PkgID: libcurl@8.4.0-r0
    PkgName: libcurl
    InstalledVersion: 8.4.0-r0
    FixedVersion: 8.5.0-r0
    Status: fixed
    Layer:
      Digest: sha256:488f0b07509d02a094ef807d52d657b749e2dddf7c3dc1c52d5dc096c0aefa0e
      DiffID: sha256:0f53fcd8f118f0b22703fd36f77cdf4c6a6bb5215782ef9bee8de0118fb4efd9
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-46219
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'curl: excessively long file name may lead to unknown HSTS status'
    Description: No description is available for this CVE.
    Severity: LOW
    References:
    - https://access.redhat.com/security/cve/CVE-2023-46219
    - https://curl.se/docs/CVE-2023-46219.html
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-46219
    - https://nvd.nist.gov/vuln/detail/CVE-2023-46219
    - https://ubuntu.com/security/notices/USN-6535-1
    - https://www.cve.org/CVERecord?id=CVE-2023-46219
- Target: Java
  Class: lang-pkgs
  Type: jar
  Vulnerabilities:
  - VulnerabilityID: CVE-2023-6378
    PkgName: ch.qos.logback:logback-classic
    PkgPath: openaf/openaf.jar
    InstalledVersion: 1.2.11
    FixedVersion: 1.3.12, 1.4.12, 1.2.13
    Status: fixed
    Layer:
      Digest: sha256:488f0b07509d02a094ef807d52d657b749e2dddf7c3dc1c52d5dc096c0aefa0e
      DiffID: sha256:0f53fcd8f118f0b22703fd36f77cdf4c6a6bb5215782ef9bee8de0118fb4efd9
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-6378
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'logback: serialization vulnerability in logback receiver'
    Description: |+
      A serialization vulnerability in logback receiver component part of 
      logback version 1.4.11 allows an attacker to mount a Denial-Of-Service 
      attack by sending poisoned data.

    Severity: HIGH
    CweIDs:
    - CWE-502
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:H
        V3Score: 7.1
      nvd:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:H
        V3Score: 7.1
    References:
    - https://access.redhat.com/security/cve/CVE-2023-6378
    - https://github.com/qos-ch/logback
    - https://github.com/qos-ch/logback/commit/9c782b45be4abdafb7e17481e24e7354c2acd1eb
    - https://github.com/qos-ch/logback/commit/b8eac23a9de9e05fb6d51160b3f46acd91af9731
    - https://github.com/qos-ch/logback/commit/bb095154be011267b64e37a1d401546e7cc2b7c3
    - https://github.com/qos-ch/logback/issues/745#issuecomment-1836227158
    - https://logback.qos.ch/manual/receivers.html
    - https://logback.qos.ch/news.html#1.2.13
    - https://logback.qos.ch/news.html#1.3.12
    - https://nvd.nist.gov/vuln/detail/CVE-2023-6378
    - https://www.cve.org/CVERecord?id=CVE-2023-6378
    PublishedDate: '2023-11-29T12:15:00Z'
    LastModifiedDate: '2023-12-05T21:00:00Z'
  - VulnerabilityID: CVE-2023-6378
    PkgName: ch.qos.logback:logback-core
    PkgPath: openaf/openaf.jar
    InstalledVersion: 1.2.11
    FixedVersion: 1.3.12, 1.4.12, 1.2.13
    Status: fixed
    Layer:
      Digest: sha256:488f0b07509d02a094ef807d52d657b749e2dddf7c3dc1c52d5dc096c0aefa0e
      DiffID: sha256:0f53fcd8f118f0b22703fd36f77cdf4c6a6bb5215782ef9bee8de0118fb4efd9
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-6378
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'logback: serialization vulnerability in logback receiver'
    Description: |+
      A serialization vulnerability in logback receiver component part of 
      logback version 1.4.11 allows an attacker to mount a Denial-Of-Service 
      attack by sending poisoned data.

    Severity: HIGH
    CweIDs:
    - CWE-502
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:H
        V3Score: 7.1
      nvd:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:H
        V3Score: 7.1
    References:
    - https://access.redhat.com/security/cve/CVE-2023-6378
    - https://github.com/qos-ch/logback
    - https://github.com/qos-ch/logback/commit/9c782b45be4abdafb7e17481e24e7354c2acd1eb
    - https://github.com/qos-ch/logback/commit/b8eac23a9de9e05fb6d51160b3f46acd91af9731
    - https://github.com/qos-ch/logback/commit/bb095154be011267b64e37a1d401546e7cc2b7c3
    - https://github.com/qos-ch/logback/issues/745#issuecomment-1836227158
    - https://logback.qos.ch/manual/receivers.html
    - https://logback.qos.ch/news.html#1.2.13
    - https://logback.qos.ch/news.html#1.3.12
    - https://nvd.nist.gov/vuln/detail/CVE-2023-6378
    - https://www.cve.org/CVERecord?id=CVE-2023-6378
    PublishedDate: '2023-11-29T12:15:00Z'
    LastModifiedDate: '2023-12-05T21:00:00Z'
