- Target: nmaguiar/socksd:build (alpine 3.20.2)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-7264
    PkgID: curl@8.9.0-r0
    PkgName: curl
    PkgIdentifier:
      PURL: pkg:apk/alpine/curl@8.9.0-r0?arch=x86_64&distro=3.20.2
      UID: 13907d381c8842c9
    InstalledVersion: 8.9.0-r0
    FixedVersion: 8.9.1-r0
    Status: fixed
    Layer:
      Digest: sha256:332813dd73ed6132a23456cfe2b2224a851d84becb032860a44061abaa33dcc9
      DiffID: sha256:987afaeac39bc98acc83bfbaa16b1dda914e372d3b93bdc47c2431cacf7d2219
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-7264
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'curl: libcurl: ASN.1 date parser overread'
    Description: |-
      libcurl's ASN1 parser code has the `GTime2str()` function, used for parsing an
      ASN.1 Generalized Time field. If given an syntactically incorrect field, the
      parser might end up using -1 for the length of the *time fraction*, leading to
      a `strlen()` getting performed on a pointer to a heap buffer area that is not
      (purposely) null terminated.

      This flaw most likely leads to a crash, but can also lead to heap contents
      getting returned to the application when
      [CURLINFO_CERTINFO](https://curl.se/libcurl/c/CURLINFO_CERTINFO.html) is used.
    Severity: MEDIUM
    CweIDs:
    - CWE-125
    VendorSeverity:
      cbl-mariner: 2
      nvd: 2
      photon: 2
      redhat: 1
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 6.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:L/I:N/A:H
        V3Score: 5.3
    References:
    - http://www.openwall.com/lists/oss-security/2024/07/31/1
    - https://access.redhat.com/security/cve/CVE-2024-7264
    - https://curl.se/docs/CVE-2024-7264.html
    - https://curl.se/docs/CVE-2024-7264.json
    - https://hackerone.com/reports/2629968
    - https://nvd.nist.gov/vuln/detail/CVE-2024-7264
    - https://ubuntu.com/security/notices/USN-6944-1
    - https://ubuntu.com/security/notices/USN-6944-2
    - https://www.cve.org/CVERecord?id=CVE-2024-7264
    PublishedDate: '2024-07-31T08:15:02.657Z'
    LastModifiedDate: '2024-08-12T17:30:51.88Z'
  - VulnerabilityID: CVE-2024-6119
    PkgID: libcrypto3@3.3.1-r3
    PkgName: libcrypto3
    PkgIdentifier:
      PURL: pkg:apk/alpine/libcrypto3@3.3.1-r3?arch=x86_64&distro=3.20.2
      UID: ed0921710eb7b515
    InstalledVersion: 3.3.1-r3
    FixedVersion: 3.3.2-r0
    Status: fixed
    Layer:
      Digest: sha256:332813dd73ed6132a23456cfe2b2224a851d84becb032860a44061abaa33dcc9
      DiffID: sha256:987afaeac39bc98acc83bfbaa16b1dda914e372d3b93bdc47c2431cacf7d2219
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-6119
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'openssl: Possible denial of service in X.509 name checks'
    Description: |-
      Issue summary: Applications performing certificate name checks (e.g., TLS
      clients checking server certificates) may attempt to read an invalid memory
      address resulting in abnormal termination of the application process.

      Impact summary: Abnormal termination of an application can a cause a denial of
      service.

      Applications performing certificate name checks (e.g., TLS clients checking
      server certificates) may attempt to read an invalid memory address when
      comparing the expected name with an `otherName` subject alternative name of an
      X.509 certificate. This may result in an exception that terminates the
      application program.

      Note that basic certificate chain validation (signatures, dates, ...) is not
      affected, the denial of service can occur only when the application also
      specifies an expected DNS name, Email address or IP address.

      TLS servers rarely solicit client certificates, and even when they do, they
      generally don't perform a name check against a reference identifier (expected
      identity), but rather extract the presented identity after checking the
      certificate chain.  So TLS servers are generally not affected and the severity
      of the issue is Moderate.

      The FIPS modules in 3.3, 3.2, 3.1 and 3.0 are not affected by this issue.
    Severity: MEDIUM
    CweIDs:
    - CWE-843
    VendorSeverity:
      redhat: 2
      ubuntu: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 5.9
    References:
    - https://access.redhat.com/security/cve/CVE-2024-6119
    - https://github.com/openssl/openssl/commit/05f360d9e849a1b277db628f1f13083a7f8dd04f
    - https://github.com/openssl/openssl/commit/06d1dc3fa96a2ba5a3e22735a033012aadc9f0d6
    - https://github.com/openssl/openssl/commit/621f3729831b05ee828a3203eddb621d014ff2b2
    - https://github.com/openssl/openssl/commit/7dfcee2cd2a63b2c64b9b4b0850be64cb695b0a0
    - https://github.com/openssl/openssl/security/advisories/GHSA-5qrj-vq78-58fj
    - https://nvd.nist.gov/vuln/detail/CVE-2024-6119
    - https://openssl-library.org/news/secadv/20240903.txt
    - https://ubuntu.com/security/notices/USN-6986-1
    - https://www.cve.org/CVERecord?id=CVE-2024-6119
    PublishedDate: '2024-09-03T16:15:07.177Z'
    LastModifiedDate: '2024-09-03T21:35:12.987Z'
  - VulnerabilityID: CVE-2024-7264
    PkgID: libcurl@8.9.0-r0
    PkgName: libcurl
    PkgIdentifier:
      PURL: pkg:apk/alpine/libcurl@8.9.0-r0?arch=x86_64&distro=3.20.2
      UID: d23fb94f69337040
    InstalledVersion: 8.9.0-r0
    FixedVersion: 8.9.1-r0
    Status: fixed
    Layer:
      Digest: sha256:332813dd73ed6132a23456cfe2b2224a851d84becb032860a44061abaa33dcc9
      DiffID: sha256:987afaeac39bc98acc83bfbaa16b1dda914e372d3b93bdc47c2431cacf7d2219
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-7264
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'curl: libcurl: ASN.1 date parser overread'
    Description: |-
      libcurl's ASN1 parser code has the `GTime2str()` function, used for parsing an
      ASN.1 Generalized Time field. If given an syntactically incorrect field, the
      parser might end up using -1 for the length of the *time fraction*, leading to
      a `strlen()` getting performed on a pointer to a heap buffer area that is not
      (purposely) null terminated.

      This flaw most likely leads to a crash, but can also lead to heap contents
      getting returned to the application when
      [CURLINFO_CERTINFO](https://curl.se/libcurl/c/CURLINFO_CERTINFO.html) is used.
    Severity: MEDIUM
    CweIDs:
    - CWE-125
    VendorSeverity:
      cbl-mariner: 2
      nvd: 2
      photon: 2
      redhat: 1
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 6.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:L/I:N/A:H
        V3Score: 5.3
    References:
    - http://www.openwall.com/lists/oss-security/2024/07/31/1
    - https://access.redhat.com/security/cve/CVE-2024-7264
    - https://curl.se/docs/CVE-2024-7264.html
    - https://curl.se/docs/CVE-2024-7264.json
    - https://hackerone.com/reports/2629968
    - https://nvd.nist.gov/vuln/detail/CVE-2024-7264
    - https://ubuntu.com/security/notices/USN-6944-1
    - https://ubuntu.com/security/notices/USN-6944-2
    - https://www.cve.org/CVERecord?id=CVE-2024-7264
    PublishedDate: '2024-07-31T08:15:02.657Z'
    LastModifiedDate: '2024-08-12T17:30:51.88Z'
  - VulnerabilityID: CVE-2024-6119
    PkgID: libssl3@3.3.1-r3
    PkgName: libssl3
    PkgIdentifier:
      PURL: pkg:apk/alpine/libssl3@3.3.1-r3?arch=x86_64&distro=3.20.2
      UID: 8ede7598835f9c6c
    InstalledVersion: 3.3.1-r3
    FixedVersion: 3.3.2-r0
    Status: fixed
    Layer:
      Digest: sha256:332813dd73ed6132a23456cfe2b2224a851d84becb032860a44061abaa33dcc9
      DiffID: sha256:987afaeac39bc98acc83bfbaa16b1dda914e372d3b93bdc47c2431cacf7d2219
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-6119
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'openssl: Possible denial of service in X.509 name checks'
    Description: |-
      Issue summary: Applications performing certificate name checks (e.g., TLS
      clients checking server certificates) may attempt to read an invalid memory
      address resulting in abnormal termination of the application process.

      Impact summary: Abnormal termination of an application can a cause a denial of
      service.

      Applications performing certificate name checks (e.g., TLS clients checking
      server certificates) may attempt to read an invalid memory address when
      comparing the expected name with an `otherName` subject alternative name of an
      X.509 certificate. This may result in an exception that terminates the
      application program.

      Note that basic certificate chain validation (signatures, dates, ...) is not
      affected, the denial of service can occur only when the application also
      specifies an expected DNS name, Email address or IP address.

      TLS servers rarely solicit client certificates, and even when they do, they
      generally don't perform a name check against a reference identifier (expected
      identity), but rather extract the presented identity after checking the
      certificate chain.  So TLS servers are generally not affected and the severity
      of the issue is Moderate.

      The FIPS modules in 3.3, 3.2, 3.1 and 3.0 are not affected by this issue.
    Severity: MEDIUM
    CweIDs:
    - CWE-843
    VendorSeverity:
      redhat: 2
      ubuntu: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 5.9
    References:
    - https://access.redhat.com/security/cve/CVE-2024-6119
    - https://github.com/openssl/openssl/commit/05f360d9e849a1b277db628f1f13083a7f8dd04f
    - https://github.com/openssl/openssl/commit/06d1dc3fa96a2ba5a3e22735a033012aadc9f0d6
    - https://github.com/openssl/openssl/commit/621f3729831b05ee828a3203eddb621d014ff2b2
    - https://github.com/openssl/openssl/commit/7dfcee2cd2a63b2c64b9b4b0850be64cb695b0a0
    - https://github.com/openssl/openssl/security/advisories/GHSA-5qrj-vq78-58fj
    - https://nvd.nist.gov/vuln/detail/CVE-2024-6119
    - https://openssl-library.org/news/secadv/20240903.txt
    - https://ubuntu.com/security/notices/USN-6986-1
    - https://www.cve.org/CVERecord?id=CVE-2024-6119
    PublishedDate: '2024-09-03T16:15:07.177Z'
    LastModifiedDate: '2024-09-03T21:35:12.987Z'
  - VulnerabilityID: CVE-2024-6119
    PkgID: openssl@3.3.1-r3
    PkgName: openssl
    PkgIdentifier:
      PURL: pkg:apk/alpine/openssl@3.3.1-r3?arch=x86_64&distro=3.20.2
      UID: 11fa069d45ee03bc
    InstalledVersion: 3.3.1-r3
    FixedVersion: 3.3.2-r0
    Status: fixed
    Layer:
      Digest: sha256:332813dd73ed6132a23456cfe2b2224a851d84becb032860a44061abaa33dcc9
      DiffID: sha256:987afaeac39bc98acc83bfbaa16b1dda914e372d3b93bdc47c2431cacf7d2219
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-6119
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'openssl: Possible denial of service in X.509 name checks'
    Description: |-
      Issue summary: Applications performing certificate name checks (e.g., TLS
      clients checking server certificates) may attempt to read an invalid memory
      address resulting in abnormal termination of the application process.

      Impact summary: Abnormal termination of an application can a cause a denial of
      service.

      Applications performing certificate name checks (e.g., TLS clients checking
      server certificates) may attempt to read an invalid memory address when
      comparing the expected name with an `otherName` subject alternative name of an
      X.509 certificate. This may result in an exception that terminates the
      application program.

      Note that basic certificate chain validation (signatures, dates, ...) is not
      affected, the denial of service can occur only when the application also
      specifies an expected DNS name, Email address or IP address.

      TLS servers rarely solicit client certificates, and even when they do, they
      generally don't perform a name check against a reference identifier (expected
      identity), but rather extract the presented identity after checking the
      certificate chain.  So TLS servers are generally not affected and the severity
      of the issue is Moderate.

      The FIPS modules in 3.3, 3.2, 3.1 and 3.0 are not affected by this issue.
    Severity: MEDIUM
    CweIDs:
    - CWE-843
    VendorSeverity:
      redhat: 2
      ubuntu: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 5.9
    References:
    - https://access.redhat.com/security/cve/CVE-2024-6119
    - https://github.com/openssl/openssl/commit/05f360d9e849a1b277db628f1f13083a7f8dd04f
    - https://github.com/openssl/openssl/commit/06d1dc3fa96a2ba5a3e22735a033012aadc9f0d6
    - https://github.com/openssl/openssl/commit/621f3729831b05ee828a3203eddb621d014ff2b2
    - https://github.com/openssl/openssl/commit/7dfcee2cd2a63b2c64b9b4b0850be64cb695b0a0
    - https://github.com/openssl/openssl/security/advisories/GHSA-5qrj-vq78-58fj
    - https://nvd.nist.gov/vuln/detail/CVE-2024-6119
    - https://openssl-library.org/news/secadv/20240903.txt
    - https://ubuntu.com/security/notices/USN-6986-1
    - https://www.cve.org/CVERecord?id=CVE-2024-6119
    PublishedDate: '2024-09-03T16:15:07.177Z'
    LastModifiedDate: '2024-09-03T21:35:12.987Z'
- Target: Java
  Class: lang-pkgs
  Type: jar
