- Target: nmaguiar/socksd:latest (alpine 3.18.4)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2023-5363
    PkgID: libcrypto3@3.1.3-r0
    PkgName: libcrypto3
    InstalledVersion: 3.1.3-r0
    FixedVersion: 3.1.4-r0
    Status: fixed
    Layer:
      Digest: sha256:fc3b305b0a6a449a0b132c8e56bf362f6a4a2d079c41ae2f3ad0e13188517621
      DiffID: sha256:4a49a7a464fc2e8d9183fd0248d321bb5d4f8f0b827d7f0a21cf7fc44adfde57
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-5363
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'Issue summary: A bug has been identified in the processing of key and  ...'
    Description: A bug has been identified in the processing of key and initialisation vector (IV) lengths. This can lead to potential truncation or overruns during the initialisation of some symmetric ciphers.
    Severity: MEDIUM
    References:
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-5363
    - https://ubuntu.com/security/notices/USN-6450-1
    - https://www.openssl.org/news/secadv/20231024.txt
  - VulnerabilityID: CVE-2023-5363
    PkgID: libssl3@3.1.3-r0
    PkgName: libssl3
    InstalledVersion: 3.1.3-r0
    FixedVersion: 3.1.4-r0
    Status: fixed
    Layer:
      Digest: sha256:fc3b305b0a6a449a0b132c8e56bf362f6a4a2d079c41ae2f3ad0e13188517621
      DiffID: sha256:4a49a7a464fc2e8d9183fd0248d321bb5d4f8f0b827d7f0a21cf7fc44adfde57
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-5363
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'Issue summary: A bug has been identified in the processing of key and  ...'
    Description: A bug has been identified in the processing of key and initialisation vector (IV) lengths. This can lead to potential truncation or overruns during the initialisation of some symmetric ciphers.
    Severity: MEDIUM
    References:
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-5363
    - https://ubuntu.com/security/notices/USN-6450-1
    - https://www.openssl.org/news/secadv/20231024.txt
  - VulnerabilityID: CVE-2023-5363
    PkgID: openssl@3.1.3-r0
    PkgName: openssl
    InstalledVersion: 3.1.3-r0
    FixedVersion: 3.1.4-r0
    Status: fixed
    Layer:
      Digest: sha256:fc3b305b0a6a449a0b132c8e56bf362f6a4a2d079c41ae2f3ad0e13188517621
      DiffID: sha256:4a49a7a464fc2e8d9183fd0248d321bb5d4f8f0b827d7f0a21cf7fc44adfde57
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-5363
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'Issue summary: A bug has been identified in the processing of key and  ...'
    Description: A bug has been identified in the processing of key and initialisation vector (IV) lengths. This can lead to potential truncation or overruns during the initialisation of some symmetric ciphers.
    Severity: MEDIUM
    References:
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-5363
    - https://ubuntu.com/security/notices/USN-6450-1
    - https://www.openssl.org/news/secadv/20231024.txt
