- Target: nmaguiar/socksd:edge (alpine 3.24.0_alpha20260127)
  Class: os-pkgs
  Type: alpine
  Packages: []
  Vulnerabilities:
  - VulnerabilityID: CVE-2026-40200
    PkgID: musl@1.2.5-r21
    PkgName: musl
    PkgIdentifier:
      PURL: pkg:apk/alpine/musl@1.2.5-r21?arch=x86_64&distro=3.24.0_alpha20260127
      UID: a7bafcf4eaef5646
    InstalledVersion: 1.2.5-r21
    FixedVersion: 1.2.6-r2
    Status: fixed
    Layer:
      Digest: sha256:ed2220f07a5ae25c88220577bd661852f0988882c89d1b2eb84f70ac831f7fe0
      DiffID: sha256:2093bb861d16dece8af7c6d8f278cc2be9939d45afdc1ab96816089b86ca2e2e
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2026-40200
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Fingerprint: sha256:749ed71dd08fee74cf457f91c1f0f2bf0656a5f15cbc9d05ce61e11275a34e50
    Title: 'musl: musl libc: Arbitrary code execution and denial of service via stack-based memory corruption in qsort'
    Description: An issue was discovered in musl libc 0.7.10 through 1.2.6. Stack-based memory corruption can occur during qsort of very large arrays, due to incorrectly implemented double-word primitives. The number of elements must exceed about seven million, i.e., the 32nd Leonardo number on 32-bit platforms (or the 64th Leonardo number on 64-bit platforms, which is not practical).
    Severity: HIGH
    CweIDs:
    - CWE-670
    VendorSeverity:
      redhat: 3
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:C/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - http://www.openwall.com/lists/oss-security/2026/04/10/13
    - https://access.redhat.com/security/cve/CVE-2026-40200
    - https://musl.libc.org/releases.html
    - https://nvd.nist.gov/vuln/detail/CVE-2026-40200
    - https://www.cve.org/CVERecord?id=CVE-2026-40200
    - https://www.openwall.com/lists/oss-security/2026/04/10/13
    PublishedDate: '2026-04-10T17:17:14.107Z'
    LastModifiedDate: '2026-04-27T19:18:46.69Z'
  - VulnerabilityID: CVE-2026-6042
    PkgID: musl@1.2.5-r21
    PkgName: musl
    PkgIdentifier:
      PURL: pkg:apk/alpine/musl@1.2.5-r21?arch=x86_64&distro=3.24.0_alpha20260127
      UID: a7bafcf4eaef5646
    InstalledVersion: 1.2.5-r21
    FixedVersion: 1.2.6-r1
    Status: fixed
    Layer:
      Digest: sha256:ed2220f07a5ae25c88220577bd661852f0988882c89d1b2eb84f70ac831f7fe0
      DiffID: sha256:2093bb861d16dece8af7c6d8f278cc2be9939d45afdc1ab96816089b86ca2e2e
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2026-6042
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Fingerprint: sha256:0bc88463ee12b1fc2c15d9e8cdab23466e65542f65d9b31a36592f0ee9a19e43
    Title: 'musl libc: GB18030 4-byte Decoder: musl libc: Denial of Service via inefficient algorithmic complexity in iconv'
    Description: A security flaw has been discovered in musl libc up to 1.2.6. Affected is the function iconv of the file src/locale/iconv.c of the component GB18030 4-byte Decoder. Performing a manipulation results in inefficient algorithmic complexity. The attack must be initiated from a local position. To fix this issue, it is recommended to deploy a patch.
    Severity: MEDIUM
    CweIDs:
    - CWE-404
    - CWE-407
    VendorSeverity:
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H
        V3Score: 5.5
    References:
    - http://www.openwall.com/lists/oss-security/2026/04/09/19
    - https://access.redhat.com/security/cve/CVE-2026-6042
    - https://nvd.nist.gov/vuln/detail/CVE-2026-6042
    - https://vuldb.com/submit/796352
    - https://vuldb.com/vuln/356620
    - https://vuldb.com/vuln/356620/cti
    - https://www.cve.org/CVERecord?id=CVE-2026-6042
    - https://www.openwall.com/lists/oss-security/2026/04/02/10
    - https://www.openwall.com/lists/oss-security/2026/04/03/2
    PublishedDate: '2026-04-10T09:16:25.45Z'
    LastModifiedDate: '2026-04-24T18:01:13.913Z'
  - VulnerabilityID: CVE-2026-40200
    PkgID: musl-utils@1.2.5-r21
    PkgName: musl-utils
    PkgIdentifier:
      PURL: pkg:apk/alpine/musl-utils@1.2.5-r21?arch=x86_64&distro=3.24.0_alpha20260127
      UID: 6f37302d99121f4f
    InstalledVersion: 1.2.5-r21
    FixedVersion: 1.2.6-r2
    Status: fixed
    Layer:
      Digest: sha256:ed2220f07a5ae25c88220577bd661852f0988882c89d1b2eb84f70ac831f7fe0
      DiffID: sha256:2093bb861d16dece8af7c6d8f278cc2be9939d45afdc1ab96816089b86ca2e2e
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2026-40200
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Fingerprint: sha256:5cf825f9664489f22a40c017514fd3812649a7029dd3c6ba2d6a02f5b658a55c
    Title: 'musl: musl libc: Arbitrary code execution and denial of service via stack-based memory corruption in qsort'
    Description: An issue was discovered in musl libc 0.7.10 through 1.2.6. Stack-based memory corruption can occur during qsort of very large arrays, due to incorrectly implemented double-word primitives. The number of elements must exceed about seven million, i.e., the 32nd Leonardo number on 32-bit platforms (or the 64th Leonardo number on 64-bit platforms, which is not practical).
    Severity: HIGH
    CweIDs:
    - CWE-670
    VendorSeverity:
      redhat: 3
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:C/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - http://www.openwall.com/lists/oss-security/2026/04/10/13
    - https://access.redhat.com/security/cve/CVE-2026-40200
    - https://musl.libc.org/releases.html
    - https://nvd.nist.gov/vuln/detail/CVE-2026-40200
    - https://www.cve.org/CVERecord?id=CVE-2026-40200
    - https://www.openwall.com/lists/oss-security/2026/04/10/13
    PublishedDate: '2026-04-10T17:17:14.107Z'
    LastModifiedDate: '2026-04-27T19:18:46.69Z'
  - VulnerabilityID: CVE-2026-6042
    PkgID: musl-utils@1.2.5-r21
    PkgName: musl-utils
    PkgIdentifier:
      PURL: pkg:apk/alpine/musl-utils@1.2.5-r21?arch=x86_64&distro=3.24.0_alpha20260127
      UID: 6f37302d99121f4f
    InstalledVersion: 1.2.5-r21
    FixedVersion: 1.2.6-r1
    Status: fixed
    Layer:
      Digest: sha256:ed2220f07a5ae25c88220577bd661852f0988882c89d1b2eb84f70ac831f7fe0
      DiffID: sha256:2093bb861d16dece8af7c6d8f278cc2be9939d45afdc1ab96816089b86ca2e2e
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2026-6042
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Fingerprint: sha256:fbd67b144ef9d52341caa3b0fd5ec520aa252ab5cfb400a01e42af68b369305d
    Title: 'musl libc: GB18030 4-byte Decoder: musl libc: Denial of Service via inefficient algorithmic complexity in iconv'
    Description: A security flaw has been discovered in musl libc up to 1.2.6. Affected is the function iconv of the file src/locale/iconv.c of the component GB18030 4-byte Decoder. Performing a manipulation results in inefficient algorithmic complexity. The attack must be initiated from a local position. To fix this issue, it is recommended to deploy a patch.
    Severity: MEDIUM
    CweIDs:
    - CWE-404
    - CWE-407
    VendorSeverity:
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H
        V3Score: 5.5
    References:
    - http://www.openwall.com/lists/oss-security/2026/04/09/19
    - https://access.redhat.com/security/cve/CVE-2026-6042
    - https://nvd.nist.gov/vuln/detail/CVE-2026-6042
    - https://vuldb.com/submit/796352
    - https://vuldb.com/vuln/356620
    - https://vuldb.com/vuln/356620/cti
    - https://www.cve.org/CVERecord?id=CVE-2026-6042
    - https://www.openwall.com/lists/oss-security/2026/04/02/10
    - https://www.openwall.com/lists/oss-security/2026/04/03/2
    PublishedDate: '2026-04-10T09:16:25.45Z'
    LastModifiedDate: '2026-04-24T18:01:13.913Z'
  - VulnerabilityID: CVE-2026-22184
    PkgID: zlib@1.3.1-r2
    PkgName: zlib
    PkgIdentifier:
      PURL: pkg:apk/alpine/zlib@1.3.1-r2?arch=x86_64&distro=3.24.0_alpha20260127
      UID: c6f558cca1be2488
    InstalledVersion: 1.3.1-r2
    FixedVersion: 1.3.2-r0
    Status: fixed
    Layer:
      Digest: sha256:ed2220f07a5ae25c88220577bd661852f0988882c89d1b2eb84f70ac831f7fe0
      DiffID: sha256:2093bb861d16dece8af7c6d8f278cc2be9939d45afdc1ab96816089b86ca2e2e
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2026-22184
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Fingerprint: sha256:73a81e67d474e260cc1797c2dde1f444a28e1df6fdfe30a042737254c375c7cd
    Title: 'zlib: zlib: Arbitrary code execution via buffer overflow in untgz utility'
    Description: zlib versions up to and including 1.3.1.2 include a global buffer overflow in the untgz utility located under contrib/untgz. The vulnerability is limited to the standalone demonstration utility and does not affect the core zlib compression library. The flaw occurs when a user executes the untgz command with an excessively long archive name supplied via the command line, leading to an out-of-bounds write in a fixed-size global buffer.
    Severity: HIGH
    CweIDs:
    - CWE-787
    VendorSeverity:
      nvd: 3
      redhat: 3
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H
        V3Score: 7.8
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:H
        V3Score: 8.6
    References:
    - https://access.redhat.com/security/cve/CVE-2026-22184
    - https://github.com/madler/zlib
    - https://github.com/madler/zlib/issues/1142
    - https://nvd.nist.gov/vuln/detail/CVE-2026-22184
    - https://seclists.org/fulldisclosure/2026/Jan/3
    - https://www.cve.org/CVERecord?id=CVE-2026-22184
    - https://www.vulncheck.com/advisories/zlib-untgz-global-buffer-overflow-in-tgzfname
    - https://zlib.net/
    PublishedDate: '2026-01-07T21:16:01.563Z'
    LastModifiedDate: '2026-03-18T16:26:31.14Z'
  - VulnerabilityID: CVE-2026-27171
    PkgID: zlib@1.3.1-r2
    PkgName: zlib
    PkgIdentifier:
      PURL: pkg:apk/alpine/zlib@1.3.1-r2?arch=x86_64&distro=3.24.0_alpha20260127
      UID: c6f558cca1be2488
    InstalledVersion: 1.3.1-r2
    FixedVersion: 1.3.2-r0
    Status: fixed
    Layer:
      Digest: sha256:ed2220f07a5ae25c88220577bd661852f0988882c89d1b2eb84f70ac831f7fe0
      DiffID: sha256:2093bb861d16dece8af7c6d8f278cc2be9939d45afdc1ab96816089b86ca2e2e
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2026-27171
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Fingerprint: sha256:1baa31af80065fcf6a1f9608e30c949177b9b7431da2a47df7aaada80437b61f
    Title: 'zlib: zlib: Denial of Service via infinite loop in CRC32 combine functions'
    Description: zlib before 1.3.2 allows CPU consumption via crc32_combine64 and crc32_combine_gen64 because x2nmodp can do right shifts within a loop that has no termination condition.
    Severity: MEDIUM
    CweIDs:
    - CWE-1284
    VendorSeverity:
      amazon: 1
      azure: 1
      cbl-mariner: 1
      julia: 1
      nvd: 2
      redhat: 1
      ubuntu: 1
    CVSS:
      julia:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:L
        V3Score: 2.9
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L
        V3Score: 3.3
    References:
    - https://7asecurity.com/blog/2026/02/zlib-7asecurity-audit
    - https://7asecurity.com/blog/2026/02/zlib-7asecurity-audit/
    - https://7asecurity.com/reports/pentest-report-zlib-RC1.1.pdf
    - https://access.redhat.com/security/cve/CVE-2026-27171
    - https://github.com/advisories/GHSA-h858-mf2m-8jf4
    - https://github.com/madler/zlib/issues/904
    - https://github.com/madler/zlib/releases/tag/v1.3.2
    - https://nvd.nist.gov/vuln/detail/CVE-2026-27171
    - https://ostif.org/zlib-audit-complete
    - https://ostif.org/zlib-audit-complete/
    - https://www.cve.org/CVERecord?id=CVE-2026-27171
    PublishedDate: '2026-02-18T04:16:01.263Z'
    LastModifiedDate: '2026-03-25T21:27:04.603Z'
- Target: Java
  Class: lang-pkgs
  Type: jar
  Packages: []
