- Target: nmaguiar/socksd:ubi-build (redhat 9.3)
  Class: os-pkgs
  Type: redhat
- Target: Java
  Class: lang-pkgs
  Type: jar
  Vulnerabilities:
  - VulnerabilityID: CVE-2023-6378
    PkgName: ch.qos.logback:logback-classic
    PkgPath: openaf/openaf.jar
    InstalledVersion: 1.2.11
    FixedVersion: 1.3.12, 1.4.12, 1.2.13
    Status: fixed
    Layer:
      Digest: sha256:e352073485ae228028169d982ca523bf82e9a0dcda9dcbf66aa33732d6ed1206
      DiffID: sha256:a6b5c5c9f0afe87b7985c2d3fc185a3dfcf2c117cff56c615c021a4a46a64ce7
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-6378
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'logback: serialization vulnerability in logback receiver'
    Description: |+
      A serialization vulnerability in logback receiver component part of 
      logback version 1.4.11 allows an attacker to mount a Denial-Of-Service 
      attack by sending poisoned data.

    Severity: HIGH
    CweIDs:
    - CWE-502
    VendorSeverity:
      ghsa: 3
      nvd: 3
      redhat: 2
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:H
        V3Score: 7.1
      nvd:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:H
        V3Score: 7.1
    References:
    - https://access.redhat.com/security/cve/CVE-2023-6378
    - https://github.com/qos-ch/logback
    - https://github.com/qos-ch/logback/commit/9c782b45be4abdafb7e17481e24e7354c2acd1eb
    - https://github.com/qos-ch/logback/commit/b8eac23a9de9e05fb6d51160b3f46acd91af9731
    - https://github.com/qos-ch/logback/commit/bb095154be011267b64e37a1d401546e7cc2b7c3
    - https://github.com/qos-ch/logback/issues/745#issuecomment-1836227158
    - https://logback.qos.ch/manual/receivers.html
    - https://logback.qos.ch/news.html#1.2.13
    - https://logback.qos.ch/news.html#1.3.12
    - https://nvd.nist.gov/vuln/detail/CVE-2023-6378
    - https://www.cve.org/CVERecord?id=CVE-2023-6378
    PublishedDate: '2023-11-29T12:15:07.543Z'
    LastModifiedDate: '2023-12-05T21:00:10.557Z'
  - VulnerabilityID: CVE-2023-6378
    PkgName: ch.qos.logback:logback-core
    PkgPath: openaf/openaf.jar
    InstalledVersion: 1.2.11
    FixedVersion: 1.3.12, 1.4.12, 1.2.13
    Status: fixed
    Layer:
      Digest: sha256:e352073485ae228028169d982ca523bf82e9a0dcda9dcbf66aa33732d6ed1206
      DiffID: sha256:a6b5c5c9f0afe87b7985c2d3fc185a3dfcf2c117cff56c615c021a4a46a64ce7
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-6378
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'logback: serialization vulnerability in logback receiver'
    Description: |+
      A serialization vulnerability in logback receiver component part of 
      logback version 1.4.11 allows an attacker to mount a Denial-Of-Service 
      attack by sending poisoned data.

    Severity: HIGH
    CweIDs:
    - CWE-502
    VendorSeverity:
      ghsa: 3
      nvd: 3
      redhat: 2
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:H
        V3Score: 7.1
      nvd:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:H
        V3Score: 7.1
    References:
    - https://access.redhat.com/security/cve/CVE-2023-6378
    - https://github.com/qos-ch/logback
    - https://github.com/qos-ch/logback/commit/9c782b45be4abdafb7e17481e24e7354c2acd1eb
    - https://github.com/qos-ch/logback/commit/b8eac23a9de9e05fb6d51160b3f46acd91af9731
    - https://github.com/qos-ch/logback/commit/bb095154be011267b64e37a1d401546e7cc2b7c3
    - https://github.com/qos-ch/logback/issues/745#issuecomment-1836227158
    - https://logback.qos.ch/manual/receivers.html
    - https://logback.qos.ch/news.html#1.2.13
    - https://logback.qos.ch/news.html#1.3.12
    - https://nvd.nist.gov/vuln/detail/CVE-2023-6378
    - https://www.cve.org/CVERecord?id=CVE-2023-6378
    PublishedDate: '2023-11-29T12:15:07.543Z'
    LastModifiedDate: '2023-12-05T21:00:10.557Z'
