- Target: nmaguiar/socksd:build (alpine 3.21.3)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-32462
    PkgID: sudo@1.9.16_p2-r0
    PkgName: sudo
    PkgIdentifier:
      PURL: pkg:apk/alpine/sudo@1.9.16_p2-r0?arch=x86_64&distro=3.21.3
      UID: de403b0ae5749724
    InstalledVersion: 1.9.16_p2-r0
    FixedVersion: 1.9.17_p1-r0
    Status: fixed
    Layer:
      Digest: sha256:74ec3e8e4bf5791f6a15e7d262e086cb52c75710e0ad23549000dc535b1b1ff1
      DiffID: sha256:9f26127c2bf2441fd5c28fa8a9cc5b40a3e60cc5fb6df565f453485bf4ddd112
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-32462
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'sudo: LPE via host option'
    Description: Sudo before 1.9.17p1, when used with a sudoers file that specifies a host that is neither the current host nor ALL, allows listed users to execute commands on unintended machines.
    Severity: HIGH
    CweIDs:
    - CWE-863
    VendorSeverity:
      alma: 3
      oracle-oval: 3
      photon: 1
      redhat: 3
      ubuntu: 3
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H
        V3Score: 7
    References:
    - https://access.redhat.com/errata/RHSA-2025:9978
    - https://access.redhat.com/security/cve/CVE-2025-32462
    - https://bugzilla.redhat.com/2374692
    - https://errata.almalinux.org/9/ALSA-2025-9978.html
    - https://linux.oracle.com/cve/CVE-2025-32462.html
    - https://linux.oracle.com/errata/ELSA-2025-9978.html
    - https://nvd.nist.gov/vuln/detail/CVE-2025-32462
    - https://ubuntu.com/security/notices/USN-7604-1
    - https://ubuntu.com/security/notices/USN-7604-2
    - https://www.cve.org/CVERecord?id=CVE-2025-32462
    - https://www.openwall.com/lists/oss-security/2025/06/30/2
    - https://www.stratascale.com/vulnerability-alert-CVE-2025-32462-sudo-host
    - https://www.sudo.ws/releases/changelog/
    - https://www.sudo.ws/security/advisories/
    - https://www.sudo.ws/security/advisories/host_any/
    PublishedDate: '2025-06-30T21:15:30.08Z'
    LastModifiedDate: '2025-07-03T15:14:12.767Z'
  - VulnerabilityID: CVE-2025-32463
    PkgID: sudo@1.9.16_p2-r0
    PkgName: sudo
    PkgIdentifier:
      PURL: pkg:apk/alpine/sudo@1.9.16_p2-r0?arch=x86_64&distro=3.21.3
      UID: de403b0ae5749724
    InstalledVersion: 1.9.16_p2-r0
    FixedVersion: 1.9.17_p1-r0
    Status: fixed
    Layer:
      Digest: sha256:74ec3e8e4bf5791f6a15e7d262e086cb52c75710e0ad23549000dc535b1b1ff1
      DiffID: sha256:9f26127c2bf2441fd5c28fa8a9cc5b40a3e60cc5fb6df565f453485bf4ddd112
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-32463
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'sudo: LPE via chroot option'
    Description: Sudo before 1.9.17p1 allows local users to obtain root access because /etc/nsswitch.conf from a user-controlled directory is used with the --chroot option.
    Severity: HIGH
    CweIDs:
    - CWE-829
    VendorSeverity:
      photon: 4
      redhat: 3
      ubuntu: 3
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - https://access.redhat.com/security/cve/CVE-2025-32463
    - https://access.redhat.com/security/cve/cve-2025-32463
    - https://bugs.gentoo.org/show_bug.cgi?id=CVE-2025-32463
    - https://explore.alas.aws.amazon.com/CVE-2025-32463.html
    - https://nvd.nist.gov/vuln/detail/CVE-2025-32463
    - https://security-tracker.debian.org/tracker/CVE-2025-32463
    - https://ubuntu.com/security/notices/USN-7604-1
    - https://www.cve.org/CVERecord?id=CVE-2025-32463
    - https://www.openwall.com/lists/oss-security/2025/06/30/3
    - https://www.stratascale.com/vulnerability-alert-CVE-2025-32463-sudo-chroot
    - https://www.sudo.ws/releases/changelog/
    - https://www.sudo.ws/security/advisories/
    - https://www.sudo.ws/security/advisories/chroot_bug/
    - https://www.suse.com/security/cve/CVE-2025-32463.html
    - https://www.suse.com/support/update/announcement/2025/suse-su-202502177-1/
    PublishedDate: '2025-06-30T21:15:30.257Z'
    LastModifiedDate: '2025-07-03T15:14:12.767Z'
- Target: Java
  Class: lang-pkgs
  Type: jar
