- Target: nmaguiar/socksd:latest (alpine 3.18.2)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2023-2975
    PkgID: libcrypto3@3.1.1-r1
    PkgName: libcrypto3
    InstalledVersion: 3.1.1-r1
    FixedVersion: 3.1.1-r2
    Layer:
      Digest: sha256:c3c464dec9406c30f68ac90ed5dede8928dd0c627602b23c1d74eef0bb6cd3d4
      DiffID: sha256:44f14a4c083fde005e8ce6fb9b037ff4f184181dcea122b36ed73ea70f922e9c
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-2975
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'Issue summary: The AES-SIV cipher implementation contains a bug that c ...'
    Description: |-
      Issue summary: The AES-SIV cipher implementation contains a bug that causes
      it to ignore empty associated data entries which are unauthenticated as
      a consequence.

      Impact summary: Applications that use the AES-SIV algorithm and want to
      authenticate empty data entries as associated data can be mislead by removing
      adding or reordering such empty entries as these are ignored by the OpenSSL
      implementation. We are currently unaware of any such applications.

      The AES-SIV algorithm allows for authentication of multiple associated
      data entries along with the encryption. To authenticate empty data the
      application has to call EVP_EncryptUpdate() (or EVP_CipherUpdate()) with
      NULL pointer as the output buffer and 0 as the input buffer length.
      The AES-SIV implementation in OpenSSL just returns success for such a call
      instead of performing the associated data authentication operation.
      The empty data thus will not be authenticated.

      As this issue does not affect non-empty associated data authentication and
      we expect it to be rare for an application to use empty associated data
      entries this is qualified as Low severity issue.
    Severity: LOW
    References:
    - http://www.openwall.com/lists/oss-security/2023/07/15/1
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-2975
    - https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=00e2f5eea29994d19293ec4e8c8775ba73678598
    - https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=6a83f0c958811f07e0d11dfc6b5a6a98edfd5bdc
    - https://www.openssl.org/news/secadv/20230714.txt
    PublishedDate: '2023-07-14T12:15:00Z'
    LastModifiedDate: '2023-07-15T13:15:00Z'
  - VulnerabilityID: CVE-2023-2975
    PkgID: libssl3@3.1.1-r1
    PkgName: libssl3
    InstalledVersion: 3.1.1-r1
    FixedVersion: 3.1.1-r2
    Layer:
      Digest: sha256:c3c464dec9406c30f68ac90ed5dede8928dd0c627602b23c1d74eef0bb6cd3d4
      DiffID: sha256:44f14a4c083fde005e8ce6fb9b037ff4f184181dcea122b36ed73ea70f922e9c
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-2975
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'Issue summary: The AES-SIV cipher implementation contains a bug that c ...'
    Description: |-
      Issue summary: The AES-SIV cipher implementation contains a bug that causes
      it to ignore empty associated data entries which are unauthenticated as
      a consequence.

      Impact summary: Applications that use the AES-SIV algorithm and want to
      authenticate empty data entries as associated data can be mislead by removing
      adding or reordering such empty entries as these are ignored by the OpenSSL
      implementation. We are currently unaware of any such applications.

      The AES-SIV algorithm allows for authentication of multiple associated
      data entries along with the encryption. To authenticate empty data the
      application has to call EVP_EncryptUpdate() (or EVP_CipherUpdate()) with
      NULL pointer as the output buffer and 0 as the input buffer length.
      The AES-SIV implementation in OpenSSL just returns success for such a call
      instead of performing the associated data authentication operation.
      The empty data thus will not be authenticated.

      As this issue does not affect non-empty associated data authentication and
      we expect it to be rare for an application to use empty associated data
      entries this is qualified as Low severity issue.
    Severity: LOW
    References:
    - http://www.openwall.com/lists/oss-security/2023/07/15/1
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-2975
    - https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=00e2f5eea29994d19293ec4e8c8775ba73678598
    - https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=6a83f0c958811f07e0d11dfc6b5a6a98edfd5bdc
    - https://www.openssl.org/news/secadv/20230714.txt
    PublishedDate: '2023-07-14T12:15:00Z'
    LastModifiedDate: '2023-07-15T13:15:00Z'
  - VulnerabilityID: CVE-2023-2975
    PkgID: openssl@3.1.1-r1
    PkgName: openssl
    InstalledVersion: 3.1.1-r1
    FixedVersion: 3.1.1-r2
    Layer:
      Digest: sha256:c3c464dec9406c30f68ac90ed5dede8928dd0c627602b23c1d74eef0bb6cd3d4
      DiffID: sha256:44f14a4c083fde005e8ce6fb9b037ff4f184181dcea122b36ed73ea70f922e9c
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-2975
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'Issue summary: The AES-SIV cipher implementation contains a bug that c ...'
    Description: |-
      Issue summary: The AES-SIV cipher implementation contains a bug that causes
      it to ignore empty associated data entries which are unauthenticated as
      a consequence.

      Impact summary: Applications that use the AES-SIV algorithm and want to
      authenticate empty data entries as associated data can be mislead by removing
      adding or reordering such empty entries as these are ignored by the OpenSSL
      implementation. We are currently unaware of any such applications.

      The AES-SIV algorithm allows for authentication of multiple associated
      data entries along with the encryption. To authenticate empty data the
      application has to call EVP_EncryptUpdate() (or EVP_CipherUpdate()) with
      NULL pointer as the output buffer and 0 as the input buffer length.
      The AES-SIV implementation in OpenSSL just returns success for such a call
      instead of performing the associated data authentication operation.
      The empty data thus will not be authenticated.

      As this issue does not affect non-empty associated data authentication and
      we expect it to be rare for an application to use empty associated data
      entries this is qualified as Low severity issue.
    Severity: LOW
    References:
    - http://www.openwall.com/lists/oss-security/2023/07/15/1
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-2975
    - https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=00e2f5eea29994d19293ec4e8c8775ba73678598
    - https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=6a83f0c958811f07e0d11dfc6b5a6a98edfd5bdc
    - https://www.openssl.org/news/secadv/20230714.txt
    PublishedDate: '2023-07-14T12:15:00Z'
    LastModifiedDate: '2023-07-15T13:15:00Z'
