- Target: nmaguiar/socksd:build (alpine 3.20.0)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2023-42364
    PkgID: busybox@1.36.1-r28
    PkgName: busybox
    PkgIdentifier:
      PURL: pkg:apk/alpine/busybox@1.36.1-r28?arch=x86_64&distro=3.20.0
      UID: a82a0980b793801d
    InstalledVersion: 1.36.1-r28
    FixedVersion: 1.36.1-r29
    Status: fixed
    Layer:
      Digest: sha256:7dd120ea30959fc4d3b532211e0a93cbb1220e9e7797d6b5d3a271ca747dfa28
      DiffID: sha256:eb6b65920066ee13a13542bc25740cf0570fe15be146173f75c1ee679ed6b828
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42364
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox: use-after-free'
    Description: A use-after-free vulnerability in BusyBox v.1.36.1 allows attackers to cause a denial of service via a crafted awk pattern in the awk.c evaluate function.
    Severity: MEDIUM
    CweIDs:
    - CWE-416
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - http://lists.busybox.net/pipermail/busybox/2024-May/090762.html
    - https://access.redhat.com/security/cve/CVE-2023-42364
    - https://bugs.busybox.net/show_bug.cgi?id=15868
    - https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/main/busybox/CVE-2023-42364-CVE-2023-42365.patch
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42364
    - https://www.cve.org/CVERecord?id=CVE-2023-42364
    PublishedDate: '2023-11-27T23:15:07.313Z'
    LastModifiedDate: '2023-11-30T05:07:10.827Z'
  - VulnerabilityID: CVE-2023-42365
    PkgID: busybox@1.36.1-r28
    PkgName: busybox
    PkgIdentifier:
      PURL: pkg:apk/alpine/busybox@1.36.1-r28?arch=x86_64&distro=3.20.0
      UID: a82a0980b793801d
    InstalledVersion: 1.36.1-r28
    FixedVersion: 1.36.1-r29
    Status: fixed
    Layer:
      Digest: sha256:7dd120ea30959fc4d3b532211e0a93cbb1220e9e7797d6b5d3a271ca747dfa28
      DiffID: sha256:eb6b65920066ee13a13542bc25740cf0570fe15be146173f75c1ee679ed6b828
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42365
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox:  use-after-free'
    Description: A use-after-free vulnerability was discovered in BusyBox v.1.36.1 via a crafted awk pattern in the awk.c copyvar function.
    Severity: MEDIUM
    CweIDs:
    - CWE-416
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - http://lists.busybox.net/pipermail/busybox/2024-May/090762.html
    - https://access.redhat.com/security/cve/CVE-2023-42365
    - https://bugs.busybox.net/show_bug.cgi?id=15871
    - https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/main/busybox/CVE-2023-42364-CVE-2023-42365.patch
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42365
    - https://www.cve.org/CVERecord?id=CVE-2023-42365
    PublishedDate: '2023-11-27T23:15:07.373Z'
    LastModifiedDate: '2023-11-30T05:08:08.77Z'
  - VulnerabilityID: CVE-2023-42364
    PkgID: busybox-binsh@1.36.1-r28
    PkgName: busybox-binsh
    PkgIdentifier:
      PURL: pkg:apk/alpine/busybox-binsh@1.36.1-r28?arch=x86_64&distro=3.20.0
      UID: 5aa0bade4a1e3de9
    InstalledVersion: 1.36.1-r28
    FixedVersion: 1.36.1-r29
    Status: fixed
    Layer:
      Digest: sha256:7dd120ea30959fc4d3b532211e0a93cbb1220e9e7797d6b5d3a271ca747dfa28
      DiffID: sha256:eb6b65920066ee13a13542bc25740cf0570fe15be146173f75c1ee679ed6b828
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42364
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox: use-after-free'
    Description: A use-after-free vulnerability in BusyBox v.1.36.1 allows attackers to cause a denial of service via a crafted awk pattern in the awk.c evaluate function.
    Severity: MEDIUM
    CweIDs:
    - CWE-416
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - http://lists.busybox.net/pipermail/busybox/2024-May/090762.html
    - https://access.redhat.com/security/cve/CVE-2023-42364
    - https://bugs.busybox.net/show_bug.cgi?id=15868
    - https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/main/busybox/CVE-2023-42364-CVE-2023-42365.patch
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42364
    - https://www.cve.org/CVERecord?id=CVE-2023-42364
    PublishedDate: '2023-11-27T23:15:07.313Z'
    LastModifiedDate: '2023-11-30T05:07:10.827Z'
  - VulnerabilityID: CVE-2023-42365
    PkgID: busybox-binsh@1.36.1-r28
    PkgName: busybox-binsh
    PkgIdentifier:
      PURL: pkg:apk/alpine/busybox-binsh@1.36.1-r28?arch=x86_64&distro=3.20.0
      UID: 5aa0bade4a1e3de9
    InstalledVersion: 1.36.1-r28
    FixedVersion: 1.36.1-r29
    Status: fixed
    Layer:
      Digest: sha256:7dd120ea30959fc4d3b532211e0a93cbb1220e9e7797d6b5d3a271ca747dfa28
      DiffID: sha256:eb6b65920066ee13a13542bc25740cf0570fe15be146173f75c1ee679ed6b828
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42365
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox:  use-after-free'
    Description: A use-after-free vulnerability was discovered in BusyBox v.1.36.1 via a crafted awk pattern in the awk.c copyvar function.
    Severity: MEDIUM
    CweIDs:
    - CWE-416
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - http://lists.busybox.net/pipermail/busybox/2024-May/090762.html
    - https://access.redhat.com/security/cve/CVE-2023-42365
    - https://bugs.busybox.net/show_bug.cgi?id=15871
    - https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/main/busybox/CVE-2023-42364-CVE-2023-42365.patch
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42365
    - https://www.cve.org/CVERecord?id=CVE-2023-42365
    PublishedDate: '2023-11-27T23:15:07.373Z'
    LastModifiedDate: '2023-11-30T05:08:08.77Z'
  - VulnerabilityID: CVE-2023-42364
    PkgID: ssl_client@1.36.1-r28
    PkgName: ssl_client
    PkgIdentifier:
      PURL: pkg:apk/alpine/ssl_client@1.36.1-r28?arch=x86_64&distro=3.20.0
      UID: 26619d38f6e1f8c8
    InstalledVersion: 1.36.1-r28
    FixedVersion: 1.36.1-r29
    Status: fixed
    Layer:
      Digest: sha256:7dd120ea30959fc4d3b532211e0a93cbb1220e9e7797d6b5d3a271ca747dfa28
      DiffID: sha256:eb6b65920066ee13a13542bc25740cf0570fe15be146173f75c1ee679ed6b828
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42364
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox: use-after-free'
    Description: A use-after-free vulnerability in BusyBox v.1.36.1 allows attackers to cause a denial of service via a crafted awk pattern in the awk.c evaluate function.
    Severity: MEDIUM
    CweIDs:
    - CWE-416
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - http://lists.busybox.net/pipermail/busybox/2024-May/090762.html
    - https://access.redhat.com/security/cve/CVE-2023-42364
    - https://bugs.busybox.net/show_bug.cgi?id=15868
    - https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/main/busybox/CVE-2023-42364-CVE-2023-42365.patch
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42364
    - https://www.cve.org/CVERecord?id=CVE-2023-42364
    PublishedDate: '2023-11-27T23:15:07.313Z'
    LastModifiedDate: '2023-11-30T05:07:10.827Z'
  - VulnerabilityID: CVE-2023-42365
    PkgID: ssl_client@1.36.1-r28
    PkgName: ssl_client
    PkgIdentifier:
      PURL: pkg:apk/alpine/ssl_client@1.36.1-r28?arch=x86_64&distro=3.20.0
      UID: 26619d38f6e1f8c8
    InstalledVersion: 1.36.1-r28
    FixedVersion: 1.36.1-r29
    Status: fixed
    Layer:
      Digest: sha256:7dd120ea30959fc4d3b532211e0a93cbb1220e9e7797d6b5d3a271ca747dfa28
      DiffID: sha256:eb6b65920066ee13a13542bc25740cf0570fe15be146173f75c1ee679ed6b828
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42365
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox:  use-after-free'
    Description: A use-after-free vulnerability was discovered in BusyBox v.1.36.1 via a crafted awk pattern in the awk.c copyvar function.
    Severity: MEDIUM
    CweIDs:
    - CWE-416
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - http://lists.busybox.net/pipermail/busybox/2024-May/090762.html
    - https://access.redhat.com/security/cve/CVE-2023-42365
    - https://bugs.busybox.net/show_bug.cgi?id=15871
    - https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/main/busybox/CVE-2023-42364-CVE-2023-42365.patch
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42365
    - https://www.cve.org/CVERecord?id=CVE-2023-42365
    PublishedDate: '2023-11-27T23:15:07.373Z'
    LastModifiedDate: '2023-11-30T05:08:08.77Z'
- Target: Java
  Class: lang-pkgs
  Type: jar
