- Target: nmaguiar/socksd:edge (alpine 3.22.0_alpha20250108)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-26519
    PkgID: musl@1.2.5-r9
    PkgName: musl
    PkgIdentifier:
      PURL: pkg:apk/alpine/musl@1.2.5-r9?arch=x86_64&distro=3.22.0_alpha20250108
      UID: ebcbb7de0538c04f
    InstalledVersion: 1.2.5-r9
    FixedVersion: 1.2.5-r10
    Status: fixed
    Layer:
      Digest: sha256:fa43a61a64ed52eed6a6ccf6fff0d34e383a6057371d819be302b07f2e5487ae
      DiffID: sha256:448f205be3a0b7e5741c7a7be44773927919dcfefc967c4014e6f0fa86ccb0eb
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-26519
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: musl libc 0.9.13 through 1.2.5 before 1.2.6 has an out-of-bounds write ...
    Description: musl libc 0.9.13 through 1.2.5 before 1.2.6 has an out-of-bounds write vulnerability when an attacker can trigger iconv conversion of untrusted EUC-KR text to UTF-8.
    Severity: UNKNOWN
    CweIDs:
    - CWE-787
    References:
    - http://www.openwall.com/lists/oss-security/2025/02/13/2
    - http://www.openwall.com/lists/oss-security/2025/02/13/3
    - http://www.openwall.com/lists/oss-security/2025/02/13/4
    - http://www.openwall.com/lists/oss-security/2025/02/13/5
    - http://www.openwall.com/lists/oss-security/2025/02/14/5
    - http://www.openwall.com/lists/oss-security/2025/02/14/6
    - https://git.musl-libc.org/cgit/musl/commit/?id=c47ad25ea3b484e10326f933e927c0bc8cded3da
    - https://git.musl-libc.org/cgit/musl/commit/?id=e5adcd97b5196e29991b524237381a0202a60659
    - https://www.openwall.com/lists/oss-security/2025/02/13/2
    PublishedDate: '2025-02-14T04:15:09.05Z'
    LastModifiedDate: '2025-02-14T17:15:23.09Z'
  - VulnerabilityID: CVE-2025-26519
    PkgID: musl-utils@1.2.5-r9
    PkgName: musl-utils
    PkgIdentifier:
      PURL: pkg:apk/alpine/musl-utils@1.2.5-r9?arch=x86_64&distro=3.22.0_alpha20250108
      UID: 8b959e5d6017bacb
    InstalledVersion: 1.2.5-r9
    FixedVersion: 1.2.5-r10
    Status: fixed
    Layer:
      Digest: sha256:fa43a61a64ed52eed6a6ccf6fff0d34e383a6057371d819be302b07f2e5487ae
      DiffID: sha256:448f205be3a0b7e5741c7a7be44773927919dcfefc967c4014e6f0fa86ccb0eb
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-26519
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: musl libc 0.9.13 through 1.2.5 before 1.2.6 has an out-of-bounds write ...
    Description: musl libc 0.9.13 through 1.2.5 before 1.2.6 has an out-of-bounds write vulnerability when an attacker can trigger iconv conversion of untrusted EUC-KR text to UTF-8.
    Severity: UNKNOWN
    CweIDs:
    - CWE-787
    References:
    - http://www.openwall.com/lists/oss-security/2025/02/13/2
    - http://www.openwall.com/lists/oss-security/2025/02/13/3
    - http://www.openwall.com/lists/oss-security/2025/02/13/4
    - http://www.openwall.com/lists/oss-security/2025/02/13/5
    - http://www.openwall.com/lists/oss-security/2025/02/14/5
    - http://www.openwall.com/lists/oss-security/2025/02/14/6
    - https://git.musl-libc.org/cgit/musl/commit/?id=c47ad25ea3b484e10326f933e927c0bc8cded3da
    - https://git.musl-libc.org/cgit/musl/commit/?id=e5adcd97b5196e29991b524237381a0202a60659
    - https://www.openwall.com/lists/oss-security/2025/02/13/2
    PublishedDate: '2025-02-14T04:15:09.05Z'
    LastModifiedDate: '2025-02-14T17:15:23.09Z'
- Target: Java
  Class: lang-pkgs
  Type: jar
