name: Scan Images

on:
  workflow_dispatch:
  schedule:
  - cron: '00 7 * * *'

jobs:
  Scan-Images:
    runs-on    : ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name       : Scan images
    steps      :
    - uses: actions/checkout@v3
      name: Checkoout

    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf

    - name: Restore the trivy databases from cache
      run : |
        wget https://openaf.io/trivy-db.tgz
        docker run --rm -v trivy-db:/volume -v $(pwd):/backup busybox tar xzf /backup/trivy-db.tgz -C /volume

    - uses: openaf/ojob-action@v4
      name: Check latest
      with:
        ojob: 'ojob.io/sec/genSecBadge'
        args: 'image=nmaguiar/socksd:latest file=.github/sec-latest.svg reportFile=.github/sec-latest.yaml'
        dist: 't8'

    - uses: openaf/ojob-action@v4
      name: Generate sec-latest.md
      with:
        ojob: 'ojob.io/util/toMDTree'
        args: 'inputFile=.github/sec-latest.yaml file=.github/sec-latest.md'
        dist: 't8'

    - uses: openaf/ojob-action@v4
      name: Check latest ubi
      with:
        ojob: 'ojob.io/sec/genSecBadge'
        args: 'image=nmaguiar/socksd:ubi file=.github/sec-ubi-latest.svg reportFile=.github/sec-ubi-latest.yaml'
        dist: 't8'
  
    - uses: openaf/ojob-action@v4
      name: Generate sec-ubi-latest.md
      with:
        ojob: 'ojob.io/util/toMDTree'
        args: 'inputFile=.github/sec-ubi-latest.yaml file=.github/sec-ubi-latest.md'
        dist: 't8'

    - uses: openaf/ojob-action@v4
      name: Check build
      with:
        ojob: 'ojob.io/sec/genSecBadge'
        args: 'image=nmaguiar/socksd:build file=.github/sec-build.svg reportFile=.github/sec-build.yaml'
        dist: 't8'

    - uses: openaf/ojob-action@v4
      name: Generate sec-build.md
      with:
        ojob: 'ojob.io/util/toMDTree'
        args: 'inputFile=.github/sec-build.yaml file=.github/sec-build.md'
        dist: 't8'

    - uses: openaf/ojob-action@v4
      name: Check build ubi
      with:
        ojob: 'ojob.io/sec/genSecBadge'
        args: 'image=nmaguiar/socksd:ubi-build file=.github/sec-ubi-build.svg reportFile=.github/sec-ubi-build.yaml'
        dist: 't8'
  
    - uses: openaf/ojob-action@v4
      name: Generate sec-ubi-build.md
      with:
        ojob: 'ojob.io/util/toMDTree'
        args: 'inputFile=.github/sec-ubi-build.yaml file=.github/sec-ubi-build.md'
        dist: 't8'

    - uses: openaf/ojob-action@v4
      name: Check build edge
      with:
        ojob: 'ojob.io/sec/genSecBadge'
        args: 'image=nmaguiar/socksd:edge file=.github/sec-edge.svg reportFile=.github/sec-edge.yaml'
        dist: 't8'
  
    - uses: openaf/ojob-action@v4
      name: Generate sec-edge-build.md
      with:
        ojob: 'ojob.io/util/toMDTree'
        args: 'inputFile=.github/sec-edge.yaml file=.github/sec-edge.md'
        dist: 't8'

    - uses: openaf/ojob-action@v4
      name: Update badges
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: 'ojob.io/git/hub/contentIn'
        args: 'message="update\ badge\ {{date}}/{{time}}" title="Update\ badge" paths=.github/'
        dist: 't8'
